version: '3'

services:
  database:
    image: mariadb:latest
    ports:
    - "3306:3306"
    user: "1000:50"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mediawiki
    volumes:
    - ./mariadb-config:/etc/mysql/conf.d
    - ./mariadb:/var/lib/mysql

  php-fpm:
    build:
      context: ./php-fpm/
    depends_on: [database]
    volumes:
    - ./webroot:/code
    ports:
    - "9000:9000"

  hhvm:
    build:
      context: ./hhvm/
    depends_on: [database]
    volumes:
    - ./webroot:/var/www/public
    ports:
      - "81:80"

  nginx:
    image: nginx:alpine
    ports:
    - "8080:80"
    depends_on: [php-fpm]
    volumes:
    - ./site.conf:/etc/nginx/conf.d/default.conf
    - ./webroot:/code
